name = "xiaohutodo"
pages_build_output_dir = ".pages-dist"
compatibility_date = "2026-06-01"

[[d1_databases]]
binding = "DB"
database_name = "xiaohutodo-db"
database_id = "f305b54c-b68f-49ed-ba32-f36b43ce014e"
migrations_dir = "migrations"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "xiaohutodo-db"
database_id = "f305b54c-b68f-49ed-ba32-f36b43ce014e"
migrations_dir = "migrations"
